resolver: lts-9.6
packages:
- location: .
- location:
    git: https://github.com/robx/configurator-pg.git
    commit: a228a834b940c341b67f8dea2e73df0554006c0d
  extra-dep: true
extra-deps:
  - Ranged-sets-0.3.0
  - protolude-0.2.2
  - hasql-1.3
  - hasql-pool-0.5
  - hasql-transaction-0.7
  - text-builder-0.5.1.1
  - jose-0.7.0.0
  - postgresql-libpq-0.9.4.1
  - http-types-0.12.3
  - wai-middleware-static-0.8.2
ghc-options:
  postgrest: -O2 -Werror -Wall -fwarn-identities -fno-warn-redundant-constraints
nix:
  shell-file: shell.nix
